/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prj.org.pisico.forms;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import prj.org.pisico.controller.pacienteController;
import prj.org.pisico.dto.listadePacientesDTO;
import prj.org.pisico.model.TbPaciente;
import prj.org.pisico.model.TbPerfil;
import prj.org.pisico.model.TbPerfilHasTbUsuario;
import prj.org.pisico.model.TbUsuario;
import prj.org.pisico.reports.em.RelatoriosEnum;
import prj.org.pisico.reports.pisico_Reports;

/**
 *
 * @author AndreBrito
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    private TbUsuario usuario;
    final javax.swing.JDesktopPane jDesktopPane12;
    private ifrmUsuario ifrmusuario;
    private ifrmStatus ifrmstatus;
    private ifrmBanco ifrmbanco;
    private ifrmCidade ifrmcidade;
    private ifrmAgenda ifrmagenda;
    private ifrmConta ifrmconta;
    private ifrmConvenio ifrmconvenio;
    private ifrmEstado ifrmestado;
    private ifrmPaciente ifrmpaciente;
    private ifrmPerfilUsuario ifrmperfilusuario;
    private ifrmCid ifrmcid;
    private ifrmInstrucao ifrminstrucao;
    private ifrmPerfil ifrmperfil;
    private ifrmProfissao ifrmprofissao;
    private ifrmParamenter ifrmParameter;
    private ifrmAppConfig ifrmAppConfig;

    public frmMain() {
        super();
        initComponents();
        this.jDesktopPane1.setSize(this.getSize());
        this.jDesktopPane12 = this.jDesktopPane1;
        this.setExtendedState(MAXIMIZED_BOTH);
        this.usuario = new TbUsuario();
        this.ifrmusuario = new ifrmUsuario();
        this.ifrmcidade = new ifrmCidade();
        this.ifrmstatus = new ifrmStatus();
        this.ifrmbanco = new ifrmBanco();
        this.ifrmagenda = new ifrmAgenda(this.usuario, this.jDesktopPane12);
        this.ifrmconta = new ifrmConta();
        this.ifrmconvenio = new ifrmConvenio();
        this.ifrmestado = new ifrmEstado();
        this.ifrmpaciente = new ifrmPaciente(this.jDesktopPane12);
        this.ifrmprofissao = new ifrmProfissao();
        this.ifrmperfil = new ifrmPerfil();
        this.ifrmcid = new ifrmCid();
        this.ifrminstrucao = new ifrmInstrucao();
        this.ifrmperfilusuario = new ifrmPerfilUsuario();
        this.ifrmParameter = new ifrmParamenter();
        this.ifrmAppConfig = new ifrmAppConfig(this.jDesktopPane12);

    }

    public frmMain(TbUsuario usuario) {
        super();
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.jDesktopPane1.setSize(this.getSize());
        this.jDesktopPane12 = this.jDesktopPane1;
        this.usuario = new TbUsuario();
        this.usuario = usuario;
        this.jLabel1.setText(this.usuario.getStrNome());
        this.jLabel4.setText("Carregando agendamentos sa semana...aguarde !!!");
        this.ifrmusuario = new ifrmUsuario();
        this.ifrmcidade = new ifrmCidade();
        this.ifrmstatus = new ifrmStatus();
        this.ifrmbanco = new ifrmBanco();
        this.ifrmagenda = new ifrmAgenda(this.usuario, this.jDesktopPane12);
        this.ifrmconvenio = new ifrmConvenio();
        this.ifrmconta = new ifrmConta();
        this.ifrmestado = new ifrmEstado();
        this.ifrmpaciente = new ifrmPaciente();        
        this.ifrmperfil = new ifrmPerfil();
        this.ifrmprofissao = new ifrmProfissao();
        this.ifrmcid = new ifrmCid();
        this.ifrminstrucao = new ifrmInstrucao();
        this.ifrmperfilusuario = new ifrmPerfilUsuario();
        this.ifrmParameter = new ifrmParamenter();
        this.ifrmAppConfig = new ifrmAppConfig(this.jDesktopPane12);
        this.analisaTelaIncial(this.usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CONTROLE DE AGENDAMENTO");
        setLocationByPlatform(true);
        setModalExclusionType(null);
        setSize(new java.awt.Dimension(600, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(51, 102, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setFocusable(false);

        jSplitPane1.setDividerLocation(510);

        jLabel1.setText("jLabel1");
        jSplitPane1.setLeftComponent(jLabel1);

        jSplitPane2.setDividerLocation(410);
        jSplitPane2.setLastDividerLocation(110);

        jLabel3.setText("jLabel3");
        jSplitPane2.setRightComponent(jLabel3);

        jLabel4.setText("jLabel4");
        jSplitPane2.setLeftComponent(jLabel4);

        jSplitPane1.setRightComponent(jSplitPane2);

        jToolBar1.add(jSplitPane1);

        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 313, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/page_add.png"))); // NOI18N
        jMenu1.setText("Novo");

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/page_white_wrench.png"))); // NOI18N
        jMenu8.setText("CID");

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/page_edit.png"))); // NOI18N
        jMenuItem16.setText("CID10");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem16);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/table.png"))); // NOI18N
        jMenuItem18.setText("SubCategoria CID");
        jMenu8.add(jMenuItem18);

        jMenu1.add(jMenu8);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/page_paste.png"))); // NOI18N
        jMenu7.setText("Pacientes");

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/user_add.png"))); // NOI18N
        jMenuItem21.setText("Novo Paciente");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/chart_organisation.png"))); // NOI18N
        jMenuItem8.setText("Convenio");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/add.png"))); // NOI18N
        jMenuItem15.setText("Profissao");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/script_gear.png"))); // NOI18N
        jMenuItem17.setText("Grau de Instrução");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/note_edit.png"))); // NOI18N
        jMenuItem10.setText("Status de Atendimento");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu1.add(jMenu7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/world.png"))); // NOI18N
        jMenu6.setText("Localidade");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/world_go.png"))); // NOI18N
        jMenuItem7.setText("Estado");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/world_edit.png"))); // NOI18N
        jMenuItem5.setText("Cidade");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenu1.add(jMenu6);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/lock.png"))); // NOI18N
        jMenu5.setText("Seguraça");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/user.png"))); // NOI18N
        jMenuItem3.setText("Usuario");
        jMenuItem3.setToolTipText("");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/group_add.png"))); // NOI18N
        jMenuItem13.setText("Perfil");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/paste_plain.png"))); // NOI18N
        jMenuItem14.setText("Perfil Usuario");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/wrench.png"))); // NOI18N
        jMenu2.setText("Movimentação");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/date.png"))); // NOI18N
        jMenuItem6.setText("Agendamento");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/report.png"))); // NOI18N
        jMenu3.setText("Relatorios");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/chart_bar_add.png"))); // NOI18N
        jMenuItem2.setText("Demonstrativo de Consultas a Receber");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/script_lightning.png"))); // NOI18N
        jMenuItem9.setText("Demonstrativo de Consultas Realizadas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/newspaper.png"))); // NOI18N
        jMenuItem19.setText("Lista de Agendamento");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/money_dollar.png"))); // NOI18N
        jMenuItem11.setText("Lista de Pacientes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/money_add.png"))); // NOI18N
        jMenuItem12.setText("Relatorio de Atendimento Por Paciente");
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/help.png"))); // NOI18N
        jMenu4.setText("Sobre");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/door_out.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/table_gear.png"))); // NOI18N
        jMenuItem4.setText("Configuração");
        jMenuItem4.setActionCommand("Configurações");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prj/icons/application_form.png"))); // NOI18N
        jMenuItem20.setText("Sobre");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        if (!ifrmperfil.isVisible()) {
            ifrmperfil.setTitle("Cadastro de Usuarios");
            jDesktopPane1.add(ifrmperfil);
            ifrmperfil.setPosicao();
            ifrmperfil.show();
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread() {
            @Override
            @SuppressWarnings("SleepWhileInLoop")
            public void run() {
                while (true) {
                    try {
                        jLabel3.setText(new SimpleDateFormat("dd/MM/yyyy hh:mm:ss").format(new Date()));
                        Thread.sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(frmMain.class
                                .getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (!ifrmusuario.isVisible()) {
            ifrmusuario.setTitle("Cadastro de Usuarios");
            jDesktopPane1.add(ifrmusuario);
            ifrmusuario.setPosicao();
            ifrmusuario.show();
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void analisaTelaIncial(TbUsuario auxUsuario) {
        int NivelAcesso = 0;
        for (Iterator i = auxUsuario.getTbPerfilHasTbUsuarioCollection().iterator(); i.hasNext();) {
            TbPerfilHasTbUsuario perfilhasUsuario = (TbPerfilHasTbUsuario) i.next();
            TbPerfil perfil = perfilhasUsuario.getTbPerfilIdPerfil();
            NivelAcesso = perfil.getIntNive();
        }

        switch (NivelAcesso) {
            case 1: {

                break;
            }
            case 2: {
                this.jMenu5.setVisible(false);
                this.jMenu6.setVisible(false);
                this.jMenuItem10.setVisible(false);

                break;
            }

            case 3: {
                this.jMenu1.setVisible(false);
                this.jMenu3.setVisible(false);
                this.jMenuItem12.setVisible(false);
                this.jMenuItem12.setVisible(false);
                this.jMenuItem9.setVisible(false);
                break;
            }
            default: {
                this.jMenu1.setVisible(false);
                this.jMenu2.setVisible(false);
                this.jMenu3.setVisible(false);
                JOptionPane.showMessageDialog(this, "Usuário sem perfil atribuido, Entre em contato com o Administrador do sistems.");
            }

        }
    }

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if (!ifrmstatus.isVisible()) {
            ifrmstatus.setTitle("Cadastro de Status de Atendimento");
            jDesktopPane1.add(ifrmstatus);
            ifrmstatus.setPosicao();
            ifrmstatus.show();
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (!ifrmestado.isVisible()) {
            ifrmestado.setTitle("Cadastro de Unidade Federativas (Estados)");
            jDesktopPane1.add(ifrmestado);
            ifrmestado.setPosicao();
            ifrmestado.show();
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (!ifrmcidade.isVisible()) {
            ifrmcidade.setTitle("Cadastro de Cidades");
            jDesktopPane1.add(ifrmcidade);
            ifrmcidade.setPosicao();
            ifrmcidade.show();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (!ifrmconvenio.isVisible()) {
            ifrmconvenio.setTitle("Cadastro de Convenios");
            jDesktopPane1.add(ifrmconvenio);
            ifrmconvenio.setPosicao();
            ifrmconvenio.show();
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        if (!ifrmperfilusuario.isVisible()) {
            ifrmperfilusuario.setTitle("Associação de Perfil ao Usuario");
            jDesktopPane1.add(ifrmperfilusuario);
            ifrmperfilusuario.setPosicao();
            ifrmperfilusuario.show();
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (!ifrmagenda.isVisible()) {
            ifrmagenda.setTitle("Agendamento de Consulta");
            jDesktopPane1.add(ifrmagenda);
            ifrmagenda.setPosicao();
            ifrmagenda.show();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        pisico_Reports rt = new pisico_Reports();
        try {
            listadePacientesDTO lp = new listadePacientesDTO();
            rt.imprimir(lp.createDto(new pacienteController().list(new TbPaciente())), RelatoriosEnum.LISTA_DE_PACIENTE);
        } catch (Exception ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        if (!ifrmprofissao.isVisible()) {
            ifrmprofissao.setTitle("Cadastro de Profissao");
            jDesktopPane1.add(ifrmprofissao);
            ifrmprofissao.setPosicao();
            ifrmprofissao.show();
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        if (!ifrminstrucao.isVisible()) {
            ifrmcid.setTitle("Cadastro de Codigo Internacional de Doenças");
            jDesktopPane1.add(ifrminstrucao);
            ifrminstrucao.setPosicao();
            ifrminstrucao.show();
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        if (!ifrmcid.isVisible()) {
            ifrmcid.setTitle("Cadastro de Codigo Internacional de Doenças");
            jDesktopPane1.add(ifrmcid);
            ifrmcid.setPosicao();
            ifrmcid.show();
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed

    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        if (!ifrmParameter.isVisible()) {
            this.ifrmParameter.setVisible(rootPaneCheckingEnabled);
            ifrmParameter.setTitle("Insira o Periodo");
            jDesktopPane1.add(ifrmParameter);
            ifrmParameter.setPosicao();
            ifrmParameter.show();
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
         if (ifrmpaciente == null) {
            this.ifrmpaciente = new ifrmPaciente(jDesktopPane12);
            if (!ifrmpaciente.isVisible()) {
                ifrmpaciente.setTitle("Cadastro de Pacientes");
                this.jDesktopPane12.add(ifrmpaciente);
                ifrmpaciente.setPosicao();
                ifrmpaciente.show();
            }
        } else {
            if (!ifrmpaciente.isVisible()) {
                ifrmpaciente.setTitle("Cadastro de Pacientes");
                this.jDesktopPane12.add(ifrmpaciente);
                ifrmpaciente.setPosicao();
                ifrmpaciente.show();
            }
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       if (!ifrmAppConfig.isVisible()) {
            this.ifrmAppConfig.setVisible(rootPaneCheckingEnabled);
            ifrmAppConfig.setTitle("Configuração do sistema");
            jDesktopPane1.add(ifrmAppConfig);
            ifrmAppConfig.setPosicao();
            ifrmAppConfig.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void SeachrCid() {
        java.awt.event.ActionEvent evt = null;
        this.jMenuItem16ActionPerformed(evt);
    }

    public void setUpLookandField() {
        try {

            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                System.out.println(info);
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
